on:
  pull_request:
    branches:
    - '**'
  push:
    branches:
    - master
name: Test
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.15.2]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./...
    - name: Tidy
      run: go mod tidy
    - name: Verify commit is clean
      run: test -z "$(git status --porcelain)" || (git status; git diff; false)
